defaults: &defaults
  port: 6379
  db: 1
  #db:
  #timeout:
  #password:
  #thread_safe:

development:
  host: 127.0.0.1
  <<: *defaults

test:
  host: 127.0.0.1
  port: 6379
  db: 15
  # Redis calls will be mock/stub'd in test mode

staging:
  host: 127.0.0.1
  <<: *defaults

demo:
  host: 127.0.0.1
  <<: *defaults  

production:
  host: 127.0.0.1
  <<: *defaults
