#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

ENV["RAILS_ENV"] = ARGV[1] || ENV["RAILS_ENV"] || "production"

rails = File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
device_server = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'device_server'))

# start/stop all instances
(1..3).each do |i|
  options = {
    :app_name   => "device_server#{i}",
    :ARGV       => ARGV,
    :dir_mode   => :normal,
    :dir        => File.join(File.dirname(__FILE__), '..', 'log'),
    :log_output => true,
    :multiple   => false,
    :backtrace  => true,
    :monitor    => false
  }

  Daemons.run_proc(options[:app_name], options) do
    require rails
    require device_server
    DeviceServer.run
  end
end