#!/usr/bin/env ruby
# This script is used to generate a series of random trips
# and points for a given device.

USER = "quentin"
DEVICE_INDEX = 0
START_DATE = Date.parse("03/07/2010")
END_DATE = Date.today

CLEAR_EXISTING = true

START_LAT = BigDecimal.new('42.78938')
START_LON = BigDecimal.new('-86.10699')

START_MILES = 10_000

# Turn off email sending
ActionMailer::Base.delivery_method = :test

########################################

user = User.find_by_login(USER)

include DeviceReport::Event

def val(bool)
  bool ? "1" : "0"
end

POSSIBLE_EVENTS = [
    # Periodic location event with ignition ON
    PERIODIC_IGNITION_ON,
    PERIODIC_HEARTBEAT,
    DIRECTION,
    RPM,
    MILEAGE,
    ACCELERATING,
    DECELERATING,
    BATTERY,
    IDLE
  ]

def random_event
  POSSIBLE_EVENTS[rand(POSSIBLE_EVENTS.length)] 
end

$current_miles = START_MILES

user.account.devices[0..20].each do |device|
  puts "Building information for device: #{device.name}"

  if CLEAR_EXISTING
    puts "\t- Clearing existing data"
    device.trips.destroy_all
    device.points.destroy_all
  end

  (START_DATE..END_DATE).each do |date|
    puts "\t- New points for #{date}"

    time = date.beginning_of_day

    # x number of trips per day
    rand(10).times do |i|
      puts "\t\t- Trip # #{i}"

      starts_at = i.hours.from_now(time)
      point_count = rand(20) + 1

      t = device.trips.create :start => starts_at
      leg = t.legs.create

      point_count.times do |i|
        puts "\t\t\t- Point #{i}"
        lat = START_LAT + (i * 0.01)
        lon = START_LON + (i * 0.02) 

        occurred_at = (i*2).minutes.from_now(starts_at)

        accelerating = rand(100) < 50
        mpg = rand(1000) / 10.0

        event = 
          if i == 1
            6011
          elsif i == point_count
            6012
          else
            random_event
          end

        $current_miles += rand(100)

        device.process(
          :latitude => lat,
          :longitude => lon,
          :altitude => 1200,
          :speed => rand(80),
          :accelerating => val(accelerating),
          :decelerating => val(!accelerating),
          :miles => $current_miles,
          :mpg => mpg,
          :date => occurred_at.to_s("%m/%d/%Y"),
          :time => occurred_at.to_s("%H:%M:%S"),
          :event => event,
          :rpm => rand(2000) + 1000
        )
      end
    end
  end
end
